# Generated by Django 4.2.6 on 2024-03-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user_double_auth_confirmationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="code",
            field=models.CharField(blank=True, default=0, max_length=6),
            preserve_default=False,
        ),
    ]
