# Generated by Django 4.2.6 on 2024-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_assignment_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_changing",
            field=models.BooleanField(default=True),
        ),
    ]
