# Generated by Django 4.2.6 on 2024-04-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_user_email_changing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_email_temp",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
