# Generated by Django 4.2.6 on 2024-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_assignment_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarynote",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
