# Generated by Django 4.2.6 on 2024-03-26 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_confirmationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmation_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
