# Generated by Django 4.2.6 on 2024-04-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diarynote_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='grades',
        ),
    ]
