# Generated by Django 4.2.6 on 2024-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_user_new_email_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_changing",
            field=models.BooleanField(default=False),
        ),
    ]
