# Generated by Django 4.2.6 on 2024-04-12 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_assignment_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarynote",
            name="emotion_type",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="diarynote",
            name="clarifying_emotion",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Loss", "Loss"),
                        ("Fear", "Fear"),
                        ("Guilt", "Guilt"),
                        ("Laziness", "Laziness"),
                        ("Interest", "Interest"),
                        ("Pride", "Pride"),
                        ("Hope", "Hope"),
                        ("Hapiness", "Hapiness"),
                        ("Anger", "Anger"),
                        ("Anxiety", "Anxiety"),
                        ("Embarrassment", "Embarrassment"),
                        ("Calmness", "Calmness"),
                        ("Inspiration", "Inspiration"),
                        ("Humility", "Humility"),
                        ("Nervousness", "Nervousness"),
                        ("Depression", "Depression"),
                        ("Shame", "Shame"),
                        ("Amazement", "Amazement"),
                        ("Euphoria", "Euphoria"),
                        ("Disgust", "Disgust"),
                        ("Sadness", "Sadness"),
                        ("Joy", "Joy"),
                        ("Respect", "Respect"),
                        ("Exhaustion", "Exhaustion"),
                        ("Impatience", "Impatience"),
                        ("Excitement", "Excitement"),
                        ("Loneliness", "Loneliness"),
                        ("Frustration", "Frustration"),
                        ("Acceptance", "Acceptance"),
                        ("Enthusiasm", "Enthusiasm"),
                        ("Love", "Love"),
                        ("Dissapointment", "Dissapointment"),
                        ("Confusion", "Confusion"),
                        ("Satisfaction", "Satisfaction"),
                        ("Self-love", "Self-love"),
                        ("Gratitude", "Gratitude"),
                    ],
                    max_length=50,
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="diarynote",
            name="event_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="diarynote",
            name="physical_sensations",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="diarynote",
            name="primary_emotion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TERRIBLE", "Terrible"),
                    ("BAD", "Bad"),
                    ("OKAY", "Okay"),
                    ("GOOD", "Good"),
                    ("GREAT", "Great"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="diarynote",
            name="thoughts_analysis",
            field=models.TextField(blank=True),
        ),
    ]
