# Generated by Django 4.2.6 on 2024-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_user_email_changing"),
        ("api", "0007_diarynote_emotion_type_and_more"),
    ]

    operations = []
