# Generated by Django 4.2.6 on 2024-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_merge_20240416_1838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_changing",
            field=models.BooleanField(default=True),
        ),
    ]
