# Generated by Django 4.2.6 on 2024-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_user_email_changing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_changing",
        ),
        migrations.AddField(
            model_name="user",
            name="new_email_changing",
            field=models.BooleanField(default=False),
        ),
    ]
