# Generated by Django 4.2.6 on 2024-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_assignment_assignment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("open", "Open"),
                    ("single", "Single"),
                    ("range", "Range"),
                    ("multiple", "Multiple"),
                ],
                max_length=10,
            ),
        ),
    ]
