# Generated by Django 4.2.6 on 2024-04-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_description_block_reply_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='reply_tags',
            new_name='description',
        ),
    ]
