# Generated by Django 4.2.6 on 2024-04-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_block_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchoice',
            options={'ordering': ['pk']},
        ),
    ]
