# Generated by Django 4.2.6 on 2024-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_diarynote_author_alter_diarynote_visible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["-add_date"]},
        ),
        migrations.AddField(
            model_name="user",
            name="date_daleted",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
