# Generated by Django 4.2.6 on 2024-06-11 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_assignment_options_user_date_daleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_daleted",
            new_name="date_deleted",
        ),
    ]
