# Generated by Django 4.2.6 on 2024-06-14 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_user_date_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_deleted",
            new_name="deleted_on",
        ),
    ]
