# Generated by Django 4.2.6 on 2024-07-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_rename_date_deleted_user_deleted_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
    ]
