# Generated by Django 4.2.6 on 2024-08-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("exercise", "Exercise"),
                    ("essay", "Essay"),
                    ("study", "Study"),
                    ("quiz", "Quiz"),
                    ("methodology", "Methodology"),
                    ("metaphor", "Metaphor"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="text",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="assignmentclient",
            name="text",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="assignmentclient",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="block",
            name="question",
            field=models.CharField(max_length=1000),
        ),
    ]
