# Generated by Django 4.2.6 on 2024-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_assignment_assignment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="question",
            field=models.CharField(max_length=3000),
        ),
    ]
