# Generated by Django 4.2.6 on 2024-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_block_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("exercise", "Exercise"),
                    ("essay", "Essay"),
                    ("study", "Study"),
                    ("quiz", "Quiz"),
                    ("methodology", "Methodology"),
                    ("metaphor", "Metaphor"),
                    ("article", "Article"),
                ],
                max_length=100,
            ),
        ),
    ]
