# Generated by Django 4.2.6 on 2024-08-30 16:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_assignment_assignment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarynote",
            name="clarifying_emotion",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Loss", "Loss"),
                        ("Fear", "Fear"),
                        ("Guilt", "Guilt"),
                        ("Laziness", "Laziness"),
                        ("Interest", "Interest"),
                        ("Pride", "Pride"),
                        ("Hope", "Hope"),
                        ("Happiness", "Happiness"),
                        ("Anger", "Anger"),
                        ("Anxiety", "Anxiety"),
                        ("Embarrassment", "Embarrassment"),
                        ("Calmness", "Calmness"),
                        ("Inspiration", "Inspiration"),
                        ("Humility", "Humility"),
                        ("Nervousness", "Nervousness"),
                        ("Depression", "Depression"),
                        ("Shame", "Shame"),
                        ("Amazement", "Amazement"),
                        ("Euphoria", "Euphoria"),
                        ("Disgust", "Disgust"),
                        ("Sadness", "Sadness"),
                        ("Joy", "Joy"),
                        ("Respect", "Respect"),
                        ("Exhaustion", "Exhaustion"),
                        ("Impatience", "Impatience"),
                        ("Excitement", "Excitement"),
                        ("Loneliness", "Loneliness"),
                        ("Frustration", "Frustration"),
                        ("Acceptance", "Acceptance"),
                        ("Enthusiasm", "Enthusiasm"),
                        ("Love", "Love"),
                        ("Disappointment", "Disappointment"),
                        ("Confusion", "Confusion"),
                        ("Satisfaction", "Satisfaction"),
                        ("Self-love", "Self-love"),
                        ("Gratitude", "Gratitude"),
                    ],
                    max_length=50,
                ),
                blank=True,
                size=None,
            ),
        ),
    ]
