# Generated by Django 4.2.6 on 2024-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_diarynote_clarifying_emotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="assignmentclient",
            name="title",
            field=models.CharField(max_length=64),
        ),
    ]
