version: "3.5"
services:
  app:
    image: ivansitnikov1/repo:latest
#    build:
#      context: .
    ports:
      - "8000:8000"
    volumes:
      - "/opt/media:/app/media/"
      - "/opt/intouch_static:/app/static/"
    depends_on:
      app-postgres:
          condition: service_healthy

  app-postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - "/opt/intouch_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: django_app
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d django_app"]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest

volumes:
  app-postgres:
    name: "app-postgres"
