version: "3.5"

volumes:
  app-postgres:
    name: "app-postgres"

services:

  app-postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - "/opt/intouch_data:/var/lib/postgresql/data"
    env_file:
     - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ivan -d django_app"]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    container_name: app
    image: ${BACKEND_IMAGE}
    ports:
      - "8000:8000"
    volumes:
      - "/opt/media:/app/media/"
      - "/opt/intouch_static:/app/static/"
    env_file:
      - .env
    environment:
      - CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}
    depends_on:
      app-postgres:
          condition: service_healthy
