# Generated by Django 4.2.6 on 2023-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('client', 'Client')], default='doctor', max_length=100),
        ),
    ]
