# Generated by Django 4.2.6 on 2023-10-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('update_date', models.DateField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('exercise', 'Exercise'), ('lesson', 'Lesson'), ('metaphor', 'Metaphor')], max_length=100)),
                ('status', models.CharField(choices=[('in progress', 'In progress'), ('publish', 'publish'), ('expansion', 'expansion')], max_length=100)),
                ('category', models.CharField(choices=[('favorites', 'Favorites'), ('trash', 'Trash'), ('library', 'Library')], default='library', max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor')),
            ],
        ),
    ]
