# Generated by Django 4.2.6 on 2023-10-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
    ]
