# Generated by Django 4.2.6 on 2023-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='category',
        ),
        migrations.AddField(
            model_name='assignment',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
