name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: create SSH-key
        run: echo "$SSH_PRIVATE_KEY" > ssh_key && chmod 600 ssh_key

      - name: Copy docker-compose.yml to server
        run: scp -i ssh_key readme.md ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/opt/test/
      
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --legacy-peer-deps

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /opt/test
          local_path: ./frontend/build/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
